/**
 * Rule Engine
 *
 * Analyzes sessions, selects relevant rules, calculates break-even,
 * and generates a CLAUDE.md tailored to the user's waste patterns.
 *
 * RULE: Pure functions only. No CLI deps.
 */

import type {
  TokenBreakdown,
  ParsedSession,
  OptimizationReport,
  OptimizationRule,
  PatternType,
} from "../types.js";
import { estimateTokens } from "../constants.js";
import { getRelevantRules, RULE_CATALOG } from "./rule-catalog.js";

/**
 * Generate an optimization report with targeted CLAUDE.md rules.
 */
export function generateOptimization(
  breakdowns: TokenBreakdown[],
  detectedPatterns: PatternType[],
): OptimizationReport {
  // Check what waste categories exist across sessions
  let hasAnySycophancy = false;
  let hasAnyMeta = false;
  let hasAnySuggestions = false;
  let hasAnyVerbose = false;

  for (const b of breakdowns) {
    for (const cat of b.categories) {
      if (cat.name === "Sycophancy" && cat.tokens > 0) hasAnySycophancy = true;
      if (cat.name === "Meta-commentary" && cat.tokens > 0) hasAnyMeta = true;
      if (cat.name === "Unsolicited Suggestions" && cat.tokens > 0) hasAnySuggestions = true;
    }
    if (b.warnings.some((w) => w.message.includes("re-reads"))) {
      detectedPatterns.push("redundant-tool");
    }
  }

  // Get relevant rules based on detected patterns
  const relevant = getRelevantRules(
    detectedPatterns,
    hasAnySycophancy,
    hasAnyMeta,
    hasAnySuggestions,
  );

  // Always include verbose output rules if sessions have high text output
  const avgOutputRatio = calculateAvgOutputRatio(breakdowns);
  if (avgOutputRatio > 0.3 || hasAnyVerbose) {
    const verboseRules = RULE_CATALOG.filter(
      (r) => r.targetPattern === "verbose-output" && !relevant.includes(r),
    );
    relevant.push(...verboseRules);
  }

  // Sort by estimated savings descending
  relevant.sort((a, b) => b.estimatedSavingsPercent - a.estimatedSavingsPercent);

  // Generate the CLAUDE.md content
  const claudeMdContent = assembleClaudeMd(relevant);
  const claudeMdTokenCost = estimateTokens(claudeMdContent);

  // Calculate total estimated savings
  const totalSavings = relevant.reduce((sum, r) => sum + r.estimatedSavingsPercent, 0);

  return {
    rules: relevant,
    totalEstimatedSavings: Math.min(totalSavings, 40), // Cap at 40% — be realistic
    claudeMdContent,
    claudeMdTokenCost,
    dataPoints: breakdowns.length,
  };
}

function assembleClaudeMd(rules: OptimizationRule[]): string {
  if (rules.length === 0) {
    return "# No optimization rules needed\n\nYour sessions are already efficient.";
  }

  const lines: string[] = [];
  lines.push("# Rules");
  lines.push("");
  lines.push("<!-- Generated by clairvoy based on your actual session data -->");
  lines.push("");

  for (const rule of rules) {
    lines.push(rule.claudeMdSnippet);
  }

  lines.push("");
  return lines.join("\n");
}

function calculateAvgOutputRatio(breakdowns: TokenBreakdown[]): number {
  if (breakdowns.length === 0) return 0;

  let totalText = 0;
  let totalOutput = 0;

  for (const b of breakdowns) {
    for (const cat of b.categories) {
      if (cat.name === "Text Explanations") totalText += cat.tokens;
      if (cat.name === "Code Output") totalOutput += cat.tokens;
    }
  }

  const total = totalText + totalOutput;
  return total > 0 ? totalText / total : 0;
}
