/**
 * clairvoy quickfix — Instant optimization with zero decisions.
 *
 * Scans 5 most recent sessions, picks the top 3 most impactful rules,
 * generates a minimal CLAUDE.md, and installs it. Under 5 seconds.
 *
 * This is the "I don't want to think, just fix it" command.
 */

import type { Command } from "commander";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import chalk from "chalk";
import { listSessions } from "../../core/parser/session-discovery.js";
import { parseSession } from "../../core/parser/session-parser.js";
import { classifySession } from "../../core/analysis/classifier.js";
import { detectAllPatterns } from "../../core/analysis/patterns.js";
import { generateOptimization } from "../../core/optimizer/rule-engine.js";
import type { PatternType } from "../../core/types.js";

export function registerQuickfixCommand(program: Command): void {
  program
    .command("quickfix")
    .description("Instant optimization — scans recent sessions, installs top rules, done")
    .option("--dry-run", "Preview rules without writing CLAUDE.md")
    .action((opts) => {
      runQuickfix(opts.dryRun ?? false);
    });
}

function runQuickfix(dryRun: boolean): void {
  const sessions = listSessions(5);
  if (sessions.length === 0) {
    console.error(chalk.red("  No sessions found. Use Claude Code first, then run quickfix."));
    process.exit(1);
  }

  console.log("");
  console.log(`${chalk.bold.cyan("  clairvoy quickfix")}${chalk.dim(" — analyzing " + sessions.length + " sessions")}`);

  // Parse and analyze
  const breakdowns = [];
  const allPatterns: PatternType[] = [];

  for (const s of sessions) {
    try {
      const parsed = parseSession(s.path);
      const breakdown = classifySession(parsed);
      breakdowns.push(breakdown);
      const patterns = detectAllPatterns(parsed);
      for (const p of patterns) {
        allPatterns.push(p.type);
      }
    } catch {
      // Skip unparseable
    }
  }

  if (breakdowns.length === 0) {
    console.error(chalk.red("  Could not parse any sessions."));
    process.exit(1);
  }

  // Generate optimization (this picks relevant rules)
  const report = generateOptimization(breakdowns, allPatterns);

  // Take only top 3 rules by estimated savings
  const topRules = report.rules.slice(0, 3);

  if (topRules.length === 0) {
    console.log("");
    console.log(chalk.green("  Your sessions look clean — no major waste patterns found."));
    console.log(chalk.dim("  Run clairvoy doctor for a deeper check."));
    console.log("");
    return;
  }

  // Build a minimal CLAUDE.md
  const lines: string[] = [];
  lines.push("# Rules");
  lines.push("");
  lines.push("<!-- Generated by clairvoy quickfix -->");
  lines.push("");
  for (const rule of topRules) {
    lines.push(rule.claudeMdSnippet);
  }
  lines.push("");
  const content = lines.join("\n");

  console.log("");
  for (const rule of topRules) {
    console.log(`  ${chalk.green("+")} ${rule.name} ${chalk.dim(`(~${rule.estimatedSavingsPercent}% savings)`)}`);
  }
  console.log("");

  if (dryRun) {
    console.log(chalk.dim("  --dry-run: not writing file"));
    console.log("");
    console.log(chalk.dim("  Would write:"));
    console.log(chalk.dim("  ─".repeat(30)));
    for (const line of content.split("\n")) {
      console.log(chalk.dim("  " + line));
    }
    console.log("");
    return;
  }

  // Write CLAUDE.md
  const claudeMdPath = join(process.cwd(), "CLAUDE.md");
  const alreadyExists = existsSync(claudeMdPath);

  if (alreadyExists) {
    // Append to existing CLAUDE.md instead of overwriting
    const existing = readFileSync(claudeMdPath, "utf-8");
    if (existing.includes("clairvoy")) {
      console.log(chalk.yellow("  CLAUDE.md already has clairvoy rules. Run clairvoy optimize --adapt to update."));
      console.log("");
      return;
    }
    writeFileSync(claudeMdPath, existing.trimEnd() + "\n\n" + content, "utf-8");
    console.log(chalk.green("  ✓ Appended 3 rules to existing CLAUDE.md"));
  } else {
    writeFileSync(claudeMdPath, content, "utf-8");
    console.log(chalk.green("  ✓ Created CLAUDE.md with top 3 rules"));
  }

  const totalSavings = topRules.reduce((s, r) => s + r.estimatedSavingsPercent, 0);
  console.log(chalk.dim(`  Estimated savings: ~${Math.min(totalSavings, 25)}% token reduction`));
  console.log("");
  console.log(`  ${chalk.dim("Want more?")} Run ${chalk.cyan("clairvoy optimize --install")} for the full 22-rule analysis.`);
  console.log("");
}
